<?xml version="1.0"?>
<robot name="QEV-3D" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- ***************** -->
    <!-- Config parameters -->
    <!-- ***************** -->

    <!--  Load the config file  -->
    <xacro:property name="config" value="${load_yaml('$(arg vehicle_config)')}"/>

    <!--  Get the parameters  -->
    <xacro:arg name="base_frame" default="base_link"/>

    <!-- Simulate sensors or not? -->
    <xacro:arg name="enable_camera" default="false"/>
    <xacro:arg name="enable_lidar" default="false"/>
    <xacro:arg name="enable_laserscan" default="false"/>

    <!-- ***************** -->
    <!-- Global parameters -->
    <!-- ***************** -->

    <xacro:property name="PI" value="3.1415926535897931"/>

    <!-- ***************** -->
    <!-- Imported elements -->
    <!-- ***************** -->

    <!--  Import the wheels  -->
    <xacro:include filename="$(find sim_vehicle)/urdf/wheels.urdf.xacro"/>

    <!-- Import all available sensors -->
    <!-- GPS -->
    <xacro:include filename="$(find sim_vehicle)/urdf/SBG_GPS.urdf.xacro"/>
    <!-- IMU -->
    <xacro:include filename="$(find sim_vehicle)/urdf/SBG_IMU.urdf.xacro"/>
    <!-- Velodyne VLP-32C -->
    <xacro:include filename="$(find sim_vehicle)/urdf/VLP-32C.urdf.xacro"/>
    <!-- ZED Stereo camera -->
    <xacro:include filename="$(find sim_vehicle)/urdf/ZED2i.urdf.xacro"/>

    <!--  Include the plugins  -->
    <!-- SBG plugin included in the SBG_IMU urdf -->
    <gazebo>
        <!-- also is ros node name -->
        <plugin name="race_car" filename="libgazebo_ros_race_car.so"></plugin>
    </gazebo>

    <gazebo>
        <plugin name="cone_detection" filename="libgazebo_ros_cone_detection.so"></plugin>
    </gazebo>

    <!-- *************** -->
    <!-- Robots Elements -->
    <!-- *************** -->

    <xacro:property name="wheel_diameter" value="0.4064"/>

    <!-- BASE FOOTPRINT -->
    <link name="${arg base_frame}"/>

    <joint name="chassis_joint" type="fixed">
      <parent link="${arg base_frame}"/>
      <child link="chassis"/>
      <origin xyz="0 0 ${wheel_diameter/2}"
              rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
    </joint>

    <link name="chassis">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="file://$(find sim_vehicle)/meshes/lando.dae"/>
        </geometry>
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="140" />
        <inertia
            ixx="16.3"
            ixy="0"
            ixz="0"
            iyy="33.6"
            iyz="0"
            izz="47.9" />
      </inertial>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="${chassis_mesh}"/>
        </geometry>
      </collision>
    </link>

    <!-- Wheels -->
    <xacro:wheels chassis_width="1.6" wheelbase="1.580"/>

    <!-- *********************************************** -->
    <!--                 MAIN SENSORS                    -->
    <!-- *********************************************** -->

    <!--     LOCATIONS: (XYZ) - original values
    IMU: 0.0 0.0 0.170
    GPS: -0.110 0.0 0.9
    LIDAR: 1.700 0.0 -0.150
    STEREO CAM: -0.110 0.0 0.800 -->

    <!--     LOCATIONS: (XYZ) - new values measured on 24/01/23
    IMU: 0.0 0.0 0.0
    GPS: 1.220 0.0 0.530
    LIDAR: 1.590 0.0 0.130
    STEREO CAM: -0.370 0.0 0.900 -->

    <xacro:SBG_IMU_sensor parent="chassis" prefix="sbg_imu">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    </xacro:SBG_IMU_sensor>

    <xacro:SBG_GPS_sensor parent="chassis" prefix="sbg_gps">
        <origin xyz="1.220 0.0 0.530" rpy="0 0 0"/>
    </xacro:SBG_GPS_sensor>

    <xacro:VLP-32C_LiDAR parent="chassis" prefix="velodyne" hz="10" lidar_active="$(arg enable_lidar)" scan_active="$(arg enable_laserscan)">
        <origin xyz="1.590 0.0 -0.15" rpy="0 0 0"/>
    </xacro:VLP-32C_LiDAR>

    <xacro:ZED2i_camera parent="chassis" prefix="zed2i" active="$(arg enable_camera)">
        <origin xyz="-0.370 0.0 0.900" rpy="0 0 0"/>
    </xacro:ZED2i_camera>
</robot>
