<?xml version="1.0"?>
<robot name="QEV-3D" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--  Load the config file  -->
    <xacro:property name="config" value="${load_yaml('$(arg vehicle_config)')}"/>

    <!--  Get the parameters  -->
    <xacro:arg name="base_frame" default="base_link"/>
    <xacro:arg name="display_car" default="true"/>

    <!-- Imports -->
    <xacro:include filename="$(find qutms_sim)/urdf/wheels.urdf.xacro"/>
    <xacro:include filename="$(find qutms_sim)/urdf/lidar.urdf.xacro"/>

    <!--  Gazebo ROS 2 plugins  -->
    <gazebo>
        <!-- this name also is ROS 2 node name -->
        <plugin name="vehicle" filename="libgazebo_vehicle.so"></plugin>
        <ros>
          <namespace>/sim</namespace>
        </ros>
    </gazebo>

    <!-- Vehicle Elements -->
    <xacro:property name="wheel_diameter" value="0.4064"/> <!-- ALSO FOUND IN wheels.urdf.xacro -->

    <material name="orange">
      <color rgba="0.88 0.36 0.035 1"/>
    </material>

    <!-- Chassis -->
    <link name="$(arg base_frame)"/>

    <xacro:property name="chassis_mesh" value="file://$(find qutms_sim)/meshes/lando.dae"/>

    <joint name="chassis_joint" type="fixed">
      <parent link="$(arg base_frame)"/>
      <child link="chassis"/>
      <!-- chassis link at wheel centre height above ground -->
      <origin xyz="0 0 ${wheel_diameter/2}" 
              rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
    </joint>

    <link name="chassis">
      <!-- Display car mesh (for RVIZ) -->
      <xacro:if value="$(arg display_car)">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="${chassis_mesh}"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="${chassis_mesh}"/>
          </geometry>
        </collision>
      </xacro:if>

      <!-- Display block car (for Foxglove) -->
      <xacro:unless value="$(arg display_car)">
        <visual>
          <origin xyz="0.3 0 0.2" rpy="0 0 0"/>
          <geometry>
            <box size="2.5 0.7 0.6"/>
          </geometry>
          <material name="orange"/>
        </visual>
        <collision>
          <origin xyz="0.3 0 0.2" rpy="0 0 0"/>
          <geometry>
            <box size="2.5 0.7 0.6"/>
          </geometry>
          <material name="orange"/>
        </collision>
      </xacro:unless>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="200" />
        <inertia
            ixx="16.3"
            ixy="0"
            ixz="0"
            iyy="33.6"
            iyz="0"
            izz="47.9" />
      </inertial>
    </link>

    <!-- Wheels -->
    <xacro:front_wheel lr_prefix="left" lr_reflect="1"/>
    <xacro:front_wheel lr_prefix="right" lr_reflect="-1"/>

    <xacro:rear_wheel lr_prefix="left" lr_reflect="1" />
    <xacro:rear_wheel lr_prefix="right" lr_reflect="-1" />

    <!-- LiDAR -->    
    <xacro:LiDAR parent="chassis" prefix="velodyne">
        <origin xyz="1.590 0.0 0.0" rpy="0 0 0"/>
    </xacro:LiDAR>
</robot>
